"""Automated cover letter generator.

Uses the pupil-labs cover letter as a structural template.
LLM generates body paragraphs; LaTeX wrapper is hardcoded.
"""

import logging
import subprocess
from pathlib import Path
from typing import Dict, Optional

from llm import generate_latex, check_ollama_available
from cv_customizer import ensure_miktex_auto_install
from cv_customizer import _is_valid_pdf

logger = logging.getLogger(__name__)

# LaTeX template — header populated from life story; body generated by LLM
COVER_LETTER_TEMPLATE = r"""%% Cover Letter — {company} — {role_title}
\documentclass[letterpaper,11pt]{{article}}

\usepackage[T1]{{fontenc}}
\usepackage[p,osf,swashQ]{{cochineal}}
\usepackage{{cabin}}
\usepackage[varqu,varl,scale=0.9]{{zi4}}
\usepackage[letterpaper,hmargin=2.5cm,top=2.2cm,bottom=2.5cm]{{geometry}}
\usepackage[dvipsnames,svgnames]{{xcolor}}
\usepackage{{hyperref}}
\usepackage{{microtype}}
\usepackage{{parskip}}
\usepackage[fixed]{{fontawesome5}}

\definecolor{{AccentColour}}{{HTML}}{{88AC0B}}
\definecolor{{MarkerColour}}{{HTML}}{{B6073F}}

\hypersetup{{colorlinks=true,allcolors=MarkerColour,breaklinks=true}}

\pagestyle{{empty}}

\newcommand{{\infoitem}}[2]{{\makebox[1.5em]{{\color{{MarkerColour!80!black}}#1}}\,#2}}

\begin{{document}}

%% ---- Header ---------------------------------------------------------------
{{\sffamily\bfseries\LARGE {author_name}}}\\[4pt]
{contact_line}

{{\color{{AccentColour}}\rule{{\linewidth}}{{2.5pt}}}}
\vspace{{1em}}

%% ---- Date & Recipient ------------------------------------------------------
\today

\medskip
\textbf{{{company}}}\\
{location}

\medskip

\textbf{{Re: {role_title_escaped}}}

\bigskip

%% ---- Body ------------------------------------------------------------------
{body}

\bigskip

Sincerely,\\[2em]
\textbf{{{author_name}}}

\end{{document}}
"""


def _extract_user_contact(life_story: str) -> dict:
    """Extract name, email, linkedin, github, website from life story."""
    import re
    info = {}
    patterns = {
        "name": r"\*\*Full Name:\*\*\s*(.+)",
        "email": r"\*\*Email:\*\*\s*(\S+@\S+)",
        "linkedin": r"\*\*LinkedIn:\*\*\s*(https?://\S+)",
        "github": r"\*\*GitHub:\*\*\s*(https?://\S+)",
        "website": r"\*\*Website:\*\*\s*(https?://\S+)",
    }
    for key, pat in patterns.items():
        m = re.search(pat, life_story[:2000])
        if m:
            info[key] = m.group(1).strip()

    # Fallback: first H1 after "Life Story —"
    if "name" not in info:
        m = re.search(r'^#\s+Life Story\s*[—–-]\s*(.+)', life_story, re.MULTILINE)
        if m:
            info["name"] = m.group(1).strip()
        else:
            info["name"] = "Candidate"

    return info


def _build_contact_line(info: dict) -> str:
    """Build a LaTeX contact info line from extracted user info."""
    parts = []
    if "email" in info:
        e = info["email"].replace("_", r"\_")
        parts.append(
            r"\infoitem{\faEnvelope[regular]}"
            r"{\href{mailto:" + info["email"] + r"}{\texttt{" + e + r"}}}"
        )
    if "linkedin" in info:
        handle = info["linkedin"].rstrip("/").split("/")[-1].replace("_", r"\_")
        parts.append(
            r"\infoitem{\faLinkedin}"
            r"{\href{" + info["linkedin"] + r"}{\texttt{" + handle + r"}}}"
        )
    if "github" in info:
        handle = info["github"].rstrip("/").split("/")[-1].replace("_", r"\_")
        parts.append(
            r"\infoitem{\faGithub}"
            r"{\href{" + info["github"] + r"}{\texttt{" + handle + r"}}}"
        )
    if "website" in info:
        url = info["website"].replace("https://", "").replace("http://", "").rstrip("/")
        url_escaped = url.replace("_", r"\_")
        parts.append(
            r"\infoitem{\faGlobe}"
            r"{\href{" + info["website"] + r"}{\texttt{" + url_escaped + r"}}}"
        )
    return r"\quad".join(parts)


def _escape_latex(text: str) -> str:
    """Escape special LaTeX characters in plain text."""
    replacements = [
        ('&', r'\&'),
        ('%', r'\%'),
        ('#', r'\#'),
        ('_', r'\_'),
    ]
    for old, new in replacements:
        text = text.replace(old, new)
    return text


def generate_cover_letter_body(
    life_story: str,
    job_analysis: Dict,
    title: str,
    company: str,
    description: str,
    model: str = "qwen3.5:9b",
) -> str:
    """Generate cover letter body paragraphs using LLM."""

    user_info = _extract_user_contact(life_story)
    user_name = user_info.get("name", "the candidate")
    user_website = user_info.get("website", "")

    system = f"""You are writing a cover letter for {user_name}.

Write in first person. Be specific and technical — reference actual projects, metrics, and technologies from their background.
Do NOT be generic. Every paragraph should connect their specific work to the specific role.
Do NOT fabricate metrics, numbers, or technologies not explicitly mentioned in their background.
Do NOT claim experience with tools or platforms not listed in their background.
If the job requires something they don't have, connect what they DO have instead.
Output LaTeX-formatted text (use \\textbf{{}} for emphasis, \\& for ampersand).
Do NOT include \\begin{{document}} or any preamble — only the body paragraphs.
Do NOT include "Dear..." salutation or "Sincerely" closing — those are handled by the template.

WRITING RULES — follow these exactly:

Sentence structure:
- Every sentence must be a direct affirmative statement with an actor, action, and measurable object.
- Do not use not-X-but-Y structures. Rewrite as a single affirmative statement.
- Do not negate a concept and restate it positively. State the positive directly.
- Do not use contrast, reversal, or reframing as a structural device.
- If emphasis is needed, add a specific detail or metric — not an opposing clause.
- One complete sentence per idea.

Prohibited constructions:
- No em dashes.
- No rhetorical fragments used for emphasis or suspense.
- No stacked parallel hype phrases (e.g. "Real X. Real Y. Real Z.").
- No sentence fragments unless they are literal UI labels or data fields.
- No abstract nouns without measurable or observable referents.
- No cadence stacking (no repeated "X. X. X." structures).
- No triadic emphasis unless each element introduces new information.
- No superlatives like "best," "top," or "ideal" unless defined by a metric.
- No "why it matters," "what it means," or "and why" endings.

Prohibited words and phrases:
leverage, cadence, touchpoint, anchor, framing, lever, moment, signal, belonging, alignment, pipeline (when used metaphorically)

Flow:
- Combine related observations when they describe the same entity or metric.
- Do not produce one fact per sentence as a list. Produce complete sentences that aggregate measurable relationships.
- Avoid promotional cadence and patterned repetition."""

    portfolio_note = f"Reference portfolio at {user_website}." if user_website else ""

    prompt = f"""Write 4 cover letter body paragraphs for this application.

TARGET ROLE: {title} at {company}
DOMAIN: {job_analysis.get('domain', 'general_ml')}
KEY TECHNOLOGIES: {', '.join(job_analysis.get('key_technologies', []))}
FOCUS AREAS: {', '.join(job_analysis.get('focus_areas', []))}
COMPANY MISSION: {job_analysis.get('company_mission', 'Not specified')}

JOB DESCRIPTION (excerpt):
{description[:2000]}

{user_name.upper()}'S FULL BACKGROUND:
{life_story[:5000]}

PARAGRAPH STRUCTURE:
1. Opening (2-3 sentences): Direct connection between their work and this specific role. Mention the role title. Show genuine excitement about the company's specific mission.
2. Main achievement (4-5 sentences): Detail the most relevant project/achievement. Include specific metrics. Reference specific technologies that overlap with job requirements.
3. Secondary expertise (3-4 sentences): Highlight other relevant work. Connect to additional job requirements.
4. Closing (2-3 sentences): Express readiness and fit for this role. {portfolio_note}

Start with "Dear {company} Team," on the first line."""

    body = generate_latex(prompt, system=system, model=model, max_tokens=2500)

    # Basic cleanup
    body = body.strip()
    if body.startswith("```"):
        lines = body.split("\n")
        body = "\n".join(l for l in lines if not l.strip().startswith("```"))

    return body


def create_cover_letter(
    app_dir: str,
    title: str,
    company: str,
    location: str,
    description: str,
    life_story: str,
    job_analysis: Dict,
    model: str = "qwen3.5:9b",
) -> Optional[str]:
    """Generate and compile a cover letter. Returns PDF path or None."""

    if not check_ollama_available():
        logger.error("Ollama not available")
        return None

    logger.info("Generating cover letter for %s at %s...", title, company)

    # Generate body
    body = generate_cover_letter_body(
        life_story=life_story,
        job_analysis=job_analysis,
        title=title,
        company=company,
        description=description,
        model=model,
    )

    if not body:
        logger.error("Failed to generate cover letter body")
        return None

    # Extract user contact info from life story
    user_info = _extract_user_contact(life_story)
    author_name = user_info.get("name", "Candidate")
    contact_line = _build_contact_line(user_info)

    # Escape role title for LaTeX Re: line
    role_title_escaped = _escape_latex(title)

    # Fill template
    tex_content = COVER_LETTER_TEMPLATE.format(
        company=_escape_latex(company),
        location=_escape_latex(location),
        role_title=title,
        role_title_escaped=role_title_escaped,
        body=body,
        author_name=author_name,
        contact_line=contact_line,
    )

    # Write and compile
    app_path = Path(app_dir)
    tex_file = app_path / "cover-letter.tex"
    tex_file.write_text(tex_content, encoding="utf-8")
    # Save preview used as email body elsewhere
    (app_path / "cover-letter.md").write_text(body, encoding="utf-8")

    def _cleanup():
        for ext in [".aux", ".fdb_latexmk", ".fls", ".log", ".out", ".synctex.gz", ".toc"]:
            aux = app_path / ("cover-letter" + ext)
            if aux.exists():
                try:
                    aux.unlink()
                except Exception:
                    pass

    pdf_path = app_path / "cover-letter.pdf"

    ensure_miktex_auto_install()

    # Prefer latexmk, but MiKTeX latexmk may require Perl on Windows.
    try:
        result = subprocess.run(
            ["latexmk", "-pdf", "-interaction=nonstopmode", "cover-letter.tex"],
            cwd=str(app_path),
            capture_output=True,
            text=True,
            timeout=180,
        )
        if _is_valid_pdf(pdf_path):
            _cleanup()
            logger.info("Cover letter generated: %s", pdf_path)
            return str(pdf_path)

        err = (result.stderr or "")[-1000:]
        if "script engine 'perl'" not in err.lower():
            logger.error("Cover letter PDF not generated. Errors:\n%s", err)
    except subprocess.TimeoutExpired:
        logger.warning("Cover letter compilation timed out (latexmk). Falling back to pdflatex.")
    except FileNotFoundError:
        logger.warning("latexmk not found. Falling back to pdflatex.")

    # Fallback: pdflatex (no perl)
    miktex_bin = Path(r"C:\Users\rebec\AppData\Local\Programs\MiKTeX\miktex\bin\x64")
    pdflatex = miktex_bin / "pdflatex.exe"
    pdflatex_cmd = str(pdflatex) if pdflatex.exists() else "pdflatex"
    try:
        for _ in range(2):
            subprocess.run(
                [pdflatex_cmd, "-interaction=nonstopmode", "cover-letter.tex"],
                cwd=str(app_path),
                capture_output=True,
                text=True,
                timeout=600,
            )
        if _is_valid_pdf(pdf_path):
            _cleanup()
            logger.info("Cover letter generated (pdflatex): %s", pdf_path)
            return str(pdf_path)
        if pdf_path.exists() and not _is_valid_pdf(pdf_path):
            try:
                pdf_path.unlink()
            except Exception:
                pass
        logger.error("Cover letter PDF not generated via pdflatex either.")
        return None
    except Exception as e:
        logger.error("pdflatex failed: %s", e)
        if pdf_path.exists() and not _is_valid_pdf(pdf_path):
            try:
                pdf_path.unlink()
            except Exception:
                pass
        return None
